name = "PMin"
license = "MIT"
licenselink = "https://github.com/pmarcowski/hugo-pmin/blob/master/LICENSE.md"
description = "Minimal Hugo theme. Based off eXtremely minimal (Xmin) theme by Yihui Xui."
homepage = "https://przemyslawmarcowski.com/blog/"
demosite = "https://przemyslawmarcowski.com/blog/"
tags = ["minimal", "blog", "personal", "clean", "simple", "starter", "minimalist"]
features = ["blog"]
min_version = "0.01"

[author]
  name = "Przemyslaw Marcowski"
  homepage = "https://przemyslawmarcowski.com/"
